name: Update URLs

on:
  schedule:
    - cron: "0 1 * * *"
  workflow_dispatch:  # 允许手动触发
  push:
    paths:
      - 'url.py'
      - 'yuan.json'

jobs:
  update-urls:
    runs-on: ubuntu-latest

    steps:
      - name: 检出代码
        uses: actions/checkout@v4

      - name: 设置 Python 环境
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: 安装依赖
        run: |
          python -m pip install --upgrade pip
          pip install requests urllib3

      - name: 运行脚本
        run: python url.py

      - name: 提交更改
        run: |
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add url.json buye.json
          git commit -m "更新 url.json 和 buye.json" && git push
